apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'api-gateway'
        static_configs:
          - targets: ['api-gateway:5001']
        metrics_path: /metrics
      - job_name: 'authentication-service'
        static_configs:
          - targets: ['authentication-service:2222']
        metrics_path: /metrics
      - job_name: 'lecturer-service'
        static_configs:
          - targets: ['lecturer-service:1113']
        metrics_path: /actuator/prometheus
      - job_name: 'payment-service'
        static_configs:
          - targets: ['payment-service:3001']
        metrics_path: /metrics
      - job_name: 'coursemanagement-service'
        static_configs:
          - targets: ['coursemanagement-service:3002']
        metrics_path: /metrics
      - job_name: 'storage-service'
        static_configs:
          - targets: ['storage-service:2345']
        metrics_path: /metrics
      - job_name: 'notification-service'
        static_configs:
          - targets: ['notification-service:1114']
        metrics_path: /metrics
      - job_name: 'support-backend'
        static_configs:
          - targets: ['support-backend:8074']
        metrics_path: /metrics
      - job_name: 'email-service'
        static_configs:
          - targets: ['email-service:8076']
        metrics_path: /metrics
      - job_name: 'certificate-service'
        static_configs:
          - targets: ['certificate-service:8080']
        metrics_path: /metrics
      - job_name: 'postgresql'
        static_configs:
          - targets: ['postgres-db:5432']
        metrics_path: /metrics
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/
        - name: prometheus-storage
          mountPath: /prometheus
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: prometheus-config
      - name: prometheus-storage
        persistentVolumeClaim:
          claimName: prometheus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
  type: ClusterIP
