version: "3.8"
services:
  
  api-gateway:
    container_name: gateway
    build: ./backend/api-gateway/
    ports:
      - "5001:5001"
    volumes:
      - ./backend/api-gateway:/app
    environment:
      - SERVICE_NAME_LEC=http://lecturer-service:1113
      - SERVICE_NAME_AUTH=http://authentication-service:2222
      - SERVICE_NAME_PAY=http://payment-service:3001
      - SERVICE_NAME_COURSE=http://coursemanagement-service:3002
      - SERVICE_NAME_NOTIFICATION=http://notification-service:1114
      - SERVICE_NAME_PROFILE=http://profile-management-SERVICE:1117
      - SERVICE_NAME_STORAGE=http://storage-service:2345

  authentication-service:
    container_name: authentication
    build: ./backend/authentication-service/
    ports:
      - "2222:2222" 
    volumes:
      - ./backend/authentication-service:/app
    environment:
      - API_KEY=apikey
      - DB=***REMOVED***authentication-service?retryWrites=true&w=majority&appName=LMS
      - JWTPRIVATEKEY=shit01
      - SALT=10

  lecturer-service:
    container_name: lecurers
    build: ./backend/lecturer-service/
    ports:
      - "1113:1113"
    volumes:
    - ./backend/lecturer-service/src:/app/src

  payment-service:
    container_name: payments
    build: ./backend/payment-service-py/
    ports:
      - "3001:3001"
    volumes:
      - ./backend/payment-service-py:/app
    environment:
      STRIPE_SECRET_KEY: "***REMOVED***"
      CLIENT_URL: "http://localhost:5173"
  coursemanagement-service:
    container_name: courses
    build: ./backend/coursemanagement-service/
    ports:
      - "3002:3002"
    volumes:
      - ./backend/coursemanagement-service:/app
    environment:
      - DB=***REMOVED***coursemanagement-service?retryWrites=true&w=majority&appName=LMS

  # notification-service:
  #   container_name: notifications
  #   build: ./backend/notification-service/
  #   ports:
  #     - "1114:1114"
  #   volumes:
  #     - ./backend/notification-service:/app
  #   environment:
  #     - PORT=1114
  #     - MONGODB_URI=mongodb+srv://

  storage-service:
    container_name: storage
    build: ./backend/storage-service/
    ports:
      - "2345:2345"
    volumes:
      - ./backend/storage-service:/app
      
  # profile-management-service:
  #     container_name: profiles
  #     build: ./backend/profile-management-service/
  #     ports:
  #       - "1117:1117"
  #     volumes:
  #       - ./backend/profile-management-service:/app
  #     environment:
  #       - PORT=1117
  #       - MONGODB_URI=mongodb+srv://zombie:boooooo@nxdun.dio0b.mongodb.net/profile-management-service?retryWrites=true&w=majority&appName=LMS
        

