version: "3.8"
services:
  authentication-service:
    container_name: authentication
    build: ./backend/authentication-service/
    ports:
      - "2222:2222" 
    volumes:
      - ./backend/authentication-service:/app
    environment:
      - API_KEY=apikey
      - DB=mongodb+srv://
      - JWTPRIVATEKEY=shit01
      - SALT=10
  api-gateway:
    container_name: gateway
    build: ./backend/api-gateway/
    ports:
      - "5000:5000"
    volumes:
      - ./backend/api-gateway:/app
    environment:
      - SERVICE_NAME_LEC=http://lecturer-service:1113
      - SERVICE_NAME_AUTH=http://authentication-service:2222
      - SERVICE_NAME_PAY=http://payment-service:3001
      - SERVICE_NAME_COURSE=http://coursemanagement-service:3002
      - SERVICE_NAME_NOTIFICATION=http://notification-service:1114
      - SERVICE_NAME_PROFILE=http://profile-management-SERVICE:1117
      - SERVICE_NAME_STORAGE=http://storage-service:2345
      - SERVICE_NAME_SUPPORT=http://localhost:1118
      - SERVICE_NAME_NOTIFICATION=http://localhost:1114/

  lecturer-service:
    container_name: lecurers
    build: ./backend/lecturer-service/
    ports:
      - "1113:1113"
    volumes:
      - ./backend/authentication-service:/app
  payment-service:
    container_name: payments
    build: ./backend/payment-service-py/
    ports:
      - "3001:3001"
    volumes:
      - ./backend/payment-service-py:/app
    environment:
      STRIPE_SECRET_KEY: "sk_test_51PBff92LxlKPHBMAiyaAfpPv4m43et8Lo3JSoce8Vy6hODBwhwcOghK5UnPWsKEqHN1B0KYScn4raFtoFaYQh5tW00MSqrccuW"
      CLIENT_URL: "http://localhost:5173"
  coursemanagement-service:
    container_name: courses
    build: ./backend/coursemanagement-service/
    ports:
      - "3002:3002"
    volumes:
      - ./backend/coursemanagement-service:/app
    environment:
      - DB=mongodb+srv://

  storage-service:
    container_name: storage
    build: ./backend/storage-service/
    ports:
      - "2345:2345"
    volumes:
      - ./backend/storage-service:/app

  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "1114:1114"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/notifydb
      - PORT=1114
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notifydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  support-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: support-backend
    restart: unless-stopped
    ports:
      - "8074:8074"
    environment:
      - MONGODB_URI=mongodb+srv://rukshan:rukshan123@cluster0.w9lemr4.mongodb.net/AssignmentAF?retryWrites=true&w=majority&appName=Cluster0
      - SECRET_KEY=mysecret
      - PORT=8074
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - lms-network
    depends_on:
      - email-service

  email-service:
    build:
      context: .
      dockerfile: dockerfile
    container_name: email-service
    restart: unless-stopped
    ports:
      - "8076:8076"
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

volumes:
  postgres_data:


