global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'support-backend'
    static_configs:
      - targets: ['host.docker.internal:1118']
    metrics_path: /metrics

  - job_name: 'email-service'
    static_configs:
      - targets: ['host.docker.internal:8076']
    metrics_path: /metrics