FROM node:20-alpine

# Create app directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy prisma schema
COPY prisma ./prisma/

# Generate Prisma client for Alpine Linux
RUN npx prisma generate

# Copy app source
COPY . .

# Expose the port the app runs on
EXPOSE 1114

# Command to run the app
CMD ["npm", "start"]