apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\nadun\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: lecturer-service
  name: lecturer-service
spec:
  ports:
    - name: "1113"
      port: 1113
      targetPort: 1113
  selector:
    io.kompose.service: lecturer-service
status:
  loadBalancer: {}
