# notification-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notify-by-udeesha:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1114
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:password@postgres:5432/notifydb"
            - name: PORT
              value: "1114"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - name: notification-volume
              mountPath: /app
      volumes:
        - name: notification-volume
          persistentVolumeClaim:
            claimName: notification-pvc
---
# notification-service-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  ports:
    - port: 1114
      targetPort: 1114
      protocol: TCP
      name: http
  selector:
    app: notification-service
---
# notification-service-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-pvc
  labels:
    app: notification-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
