apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\nadun\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: notification-service
  name: notification-service
spec:
  ports:
    - name: "1114"
      port: 1114
      targetPort: 1114
  selector:
    io.kompose.service: notification-service
status:
  loadBalancer: {}
